version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    allow:
      - dependency-type: "production"
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"